# Generated by Django 3.0.7 on 2020-06-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('duration', models.IntegerField()),
                ('reparto', models.TextField()),
                ('showing', models.BooleanField()),
                ('director', models.CharField(max_length=120)),
                ('genre', models.CharField(max_length=120)),
                ('language', models.CharField(max_length=120)),
                ('synopsis', models.TextField()),
            ],
        ),
    ]
